#define TF_RADIO_ID(baseClass,displayNameBase,index) class baseClass##_##index : baseClass \
    { \
        displayName = 'displayNameBase index'; \
        scope = 1; \
        scopeCurator = 1; \
        tf_prototype = 0; \
        tf_radio = 1; \
        ace_arsenal_uniqueBase = baseClass; \
    };

#define TF_RADIO_ID_LIST(baseClass,displayNameBase) \
TF_RADIO_ID(baseClass,displayNameBase,1) \
TF_RADIO_ID(baseClass,displayNameBase,2) \
TF_RADIO_ID(baseClass,displayNameBase,3) \
TF_RADIO_ID(baseClass,displayNameBase,4) \
TF_RADIO_ID(baseClass,displayNameBase,5) \
TF_RADIO_ID(baseClass,displayNameBase,6) \
TF_RADIO_ID(baseClass,displayNameBase,7) \
TF_RADIO_ID(baseClass,displayNameBase,8) \
TF_RADIO_ID(baseClass,displayNameBase,9) \
TF_RADIO_ID(baseClass,displayNameBase,10) \
TF_RADIO_ID(baseClass,displayNameBase,11) \
TF_RADIO_ID(baseClass,displayNameBase,12) \
TF_RADIO_ID(baseClass,displayNameBase,13) \
TF_RADIO_ID(baseClass,displayNameBase,14) \
TF_RADIO_ID(baseClass,displayNameBase,15) \
TF_RADIO_ID(baseClass,displayNameBase,16) \
TF_RADIO_ID(baseClass,displayNameBase,17) \
TF_RADIO_ID(baseClass,displayNameBase,18) \
TF_RADIO_ID(baseClass,displayNameBase,19) \
TF_RADIO_ID(baseClass,displayNameBase,20) \
TF_RADIO_ID(baseClass,displayNameBase,21) \
TF_RADIO_ID(baseClass,displayNameBase,22) \
TF_RADIO_ID(baseClass,displayNameBase,23) \
TF_RADIO_ID(baseClass,displayNameBase,24) \
TF_RADIO_ID(baseClass,displayNameBase,25) \
TF_RADIO_ID(baseClass,displayNameBase,26) \
TF_RADIO_ID(baseClass,displayNameBase,27) \
TF_RADIO_ID(baseClass,displayNameBase,28) \
TF_RADIO_ID(baseClass,displayNameBase,29) \
TF_RADIO_ID(baseClass,displayNameBase,30) \
TF_RADIO_ID(baseClass,displayNameBase,31) \
TF_RADIO_ID(baseClass,displayNameBase,32) \
TF_RADIO_ID(baseClass,displayNameBase,33) \
TF_RADIO_ID(baseClass,displayNameBase,34) \
TF_RADIO_ID(baseClass,displayNameBase,35) \
TF_RADIO_ID(baseClass,displayNameBase,36) \
TF_RADIO_ID(baseClass,displayNameBase,37) \
TF_RADIO_ID(baseClass,displayNameBase,38) \
TF_RADIO_ID(baseClass,displayNameBase,39) \
TF_RADIO_ID(baseClass,displayNameBase,40) \
TF_RADIO_ID(baseClass,displayNameBase,41) \
TF_RADIO_ID(baseClass,displayNameBase,42) \
TF_RADIO_ID(baseClass,displayNameBase,43) \
TF_RADIO_ID(baseClass,displayNameBase,44) \
TF_RADIO_ID(baseClass,displayNameBase,45) \
TF_RADIO_ID(baseClass,displayNameBase,46) \
TF_RADIO_ID(baseClass,displayNameBase,47) \
TF_RADIO_ID(baseClass,displayNameBase,48) \
TF_RADIO_ID(baseClass,displayNameBase,49) \
TF_RADIO_ID(baseClass,displayNameBase,50) \
TF_RADIO_ID(baseClass,displayNameBase,51) \
TF_RADIO_ID(baseClass,displayNameBase,52) \
TF_RADIO_ID(baseClass,displayNameBase,53) \
TF_RADIO_ID(baseClass,displayNameBase,54) \
TF_RADIO_ID(baseClass,displayNameBase,55) \
TF_RADIO_ID(baseClass,displayNameBase,56) \
TF_RADIO_ID(baseClass,displayNameBase,57) \
TF_RADIO_ID(baseClass,displayNameBase,58) \
TF_RADIO_ID(baseClass,displayNameBase,59) \
TF_RADIO_ID(baseClass,displayNameBase,60) \
TF_RADIO_ID(baseClass,displayNameBase,61) \
TF_RADIO_ID(baseClass,displayNameBase,62) \
TF_RADIO_ID(baseClass,displayNameBase,63) \
TF_RADIO_ID(baseClass,displayNameBase,64) \
TF_RADIO_ID(baseClass,displayNameBase,65) \
TF_RADIO_ID(baseClass,displayNameBase,66) \
TF_RADIO_ID(baseClass,displayNameBase,67) \
TF_RADIO_ID(baseClass,displayNameBase,68) \
TF_RADIO_ID(baseClass,displayNameBase,69) \
TF_RADIO_ID(baseClass,displayNameBase,70) \
TF_RADIO_ID(baseClass,displayNameBase,71) \
TF_RADIO_ID(baseClass,displayNameBase,72) \
TF_RADIO_ID(baseClass,displayNameBase,73) \
TF_RADIO_ID(baseClass,displayNameBase,74) \
TF_RADIO_ID(baseClass,displayNameBase,75) \
TF_RADIO_ID(baseClass,displayNameBase,76) \
TF_RADIO_ID(baseClass,displayNameBase,77) \
TF_RADIO_ID(baseClass,displayNameBase,78) \
TF_RADIO_ID(baseClass,displayNameBase,79) \
TF_RADIO_ID(baseClass,displayNameBase,80) \
TF_RADIO_ID(baseClass,displayNameBase,81) \
TF_RADIO_ID(baseClass,displayNameBase,82) \
TF_RADIO_ID(baseClass,displayNameBase,83) \
TF_RADIO_ID(baseClass,displayNameBase,84) \
TF_RADIO_ID(baseClass,displayNameBase,85) \
TF_RADIO_ID(baseClass,displayNameBase,86) \
TF_RADIO_ID(baseClass,displayNameBase,87) \
TF_RADIO_ID(baseClass,displayNameBase,88) \
TF_RADIO_ID(baseClass,displayNameBase,89) \
TF_RADIO_ID(baseClass,displayNameBase,90) \
TF_RADIO_ID(baseClass,displayNameBase,91) \
TF_RADIO_ID(baseClass,displayNameBase,92) \
TF_RADIO_ID(baseClass,displayNameBase,93) \
TF_RADIO_ID(baseClass,displayNameBase,94) \
TF_RADIO_ID(baseClass,displayNameBase,95) \
TF_RADIO_ID(baseClass,displayNameBase,96) \
TF_RADIO_ID(baseClass,displayNameBase,97) \
TF_RADIO_ID(baseClass,displayNameBase,98) \
TF_RADIO_ID(baseClass,displayNameBase,99) \
TF_RADIO_ID(baseClass,displayNameBase,100) \
TF_RADIO_ID(baseClass,displayNameBase,101) \
TF_RADIO_ID(baseClass,displayNameBase,102) \
TF_RADIO_ID(baseClass,displayNameBase,103) \
TF_RADIO_ID(baseClass,displayNameBase,104) \
TF_RADIO_ID(baseClass,displayNameBase,105) \
TF_RADIO_ID(baseClass,displayNameBase,106) \
TF_RADIO_ID(baseClass,displayNameBase,107) \
TF_RADIO_ID(baseClass,displayNameBase,108) \
TF_RADIO_ID(baseClass,displayNameBase,109) \
TF_RADIO_ID(baseClass,displayNameBase,110) \
TF_RADIO_ID(baseClass,displayNameBase,111) \
TF_RADIO_ID(baseClass,displayNameBase,112) \
TF_RADIO_ID(baseClass,displayNameBase,113) \
TF_RADIO_ID(baseClass,displayNameBase,114) \
TF_RADIO_ID(baseClass,displayNameBase,115) \
TF_RADIO_ID(baseClass,displayNameBase,116) \
TF_RADIO_ID(baseClass,displayNameBase,117) \
TF_RADIO_ID(baseClass,displayNameBase,118) \
TF_RADIO_ID(baseClass,displayNameBase,119) \
TF_RADIO_ID(baseClass,displayNameBase,120) \
TF_RADIO_ID(baseClass,displayNameBase,121) \
TF_RADIO_ID(baseClass,displayNameBase,122) \
TF_RADIO_ID(baseClass,displayNameBase,123) \
TF_RADIO_ID(baseClass,displayNameBase,124) \
TF_RADIO_ID(baseClass,displayNameBase,125) \
TF_RADIO_ID(baseClass,displayNameBase,126) \
TF_RADIO_ID(baseClass,displayNameBase,127) \
TF_RADIO_ID(baseClass,displayNameBase,128) \
TF_RADIO_ID(baseClass,displayNameBase,129) \
TF_RADIO_ID(baseClass,displayNameBase,130) \
TF_RADIO_ID(baseClass,displayNameBase,131) \
TF_RADIO_ID(baseClass,displayNameBase,132) \
TF_RADIO_ID(baseClass,displayNameBase,133) \
TF_RADIO_ID(baseClass,displayNameBase,134) \
TF_RADIO_ID(baseClass,displayNameBase,135) \
TF_RADIO_ID(baseClass,displayNameBase,136) \
TF_RADIO_ID(baseClass,displayNameBase,137) \
TF_RADIO_ID(baseClass,displayNameBase,138) \
TF_RADIO_ID(baseClass,displayNameBase,139) \
TF_RADIO_ID(baseClass,displayNameBase,140) \
TF_RADIO_ID(baseClass,displayNameBase,141) \
TF_RADIO_ID(baseClass,displayNameBase,142) \
TF_RADIO_ID(baseClass,displayNameBase,143) \
TF_RADIO_ID(baseClass,displayNameBase,144) \
TF_RADIO_ID(baseClass,displayNameBase,145) \
TF_RADIO_ID(baseClass,displayNameBase,146) \
TF_RADIO_ID(baseClass,displayNameBase,147) \
TF_RADIO_ID(baseClass,displayNameBase,148) \
TF_RADIO_ID(baseClass,displayNameBase,149) \
TF_RADIO_ID(baseClass,displayNameBase,150) \
TF_RADIO_ID(baseClass,displayNameBase,151) \
TF_RADIO_ID(baseClass,displayNameBase,152) \
TF_RADIO_ID(baseClass,displayNameBase,153) \
TF_RADIO_ID(baseClass,displayNameBase,154) \
TF_RADIO_ID(baseClass,displayNameBase,155) \
TF_RADIO_ID(baseClass,displayNameBase,156) \
TF_RADIO_ID(baseClass,displayNameBase,157) \
TF_RADIO_ID(baseClass,displayNameBase,158) \
TF_RADIO_ID(baseClass,displayNameBase,159) \
TF_RADIO_ID(baseClass,displayNameBase,160) \
TF_RADIO_ID(baseClass,displayNameBase,161) \
TF_RADIO_ID(baseClass,displayNameBase,162) \
TF_RADIO_ID(baseClass,displayNameBase,163) \
TF_RADIO_ID(baseClass,displayNameBase,164) \
TF_RADIO_ID(baseClass,displayNameBase,165) \
TF_RADIO_ID(baseClass,displayNameBase,166) \
TF_RADIO_ID(baseClass,displayNameBase,167) \
TF_RADIO_ID(baseClass,displayNameBase,168) \
TF_RADIO_ID(baseClass,displayNameBase,169) \
TF_RADIO_ID(baseClass,displayNameBase,170) \
TF_RADIO_ID(baseClass,displayNameBase,171) \
TF_RADIO_ID(baseClass,displayNameBase,172) \
TF_RADIO_ID(baseClass,displayNameBase,173) \
TF_RADIO_ID(baseClass,displayNameBase,174) \
TF_RADIO_ID(baseClass,displayNameBase,175) \
TF_RADIO_ID(baseClass,displayNameBase,176) \
TF_RADIO_ID(baseClass,displayNameBase,177) \
TF_RADIO_ID(baseClass,displayNameBase,178) \
TF_RADIO_ID(baseClass,displayNameBase,179) \
TF_RADIO_ID(baseClass,displayNameBase,180) \
TF_RADIO_ID(baseClass,displayNameBase,181) \
TF_RADIO_ID(baseClass,displayNameBase,182) \
TF_RADIO_ID(baseClass,displayNameBase,183) \
TF_RADIO_ID(baseClass,displayNameBase,184) \
TF_RADIO_ID(baseClass,displayNameBase,185) \
TF_RADIO_ID(baseClass,displayNameBase,186) \
TF_RADIO_ID(baseClass,displayNameBase,187) \
TF_RADIO_ID(baseClass,displayNameBase,188) \
TF_RADIO_ID(baseClass,displayNameBase,189) \
TF_RADIO_ID(baseClass,displayNameBase,190) \
TF_RADIO_ID(baseClass,displayNameBase,191) \
TF_RADIO_ID(baseClass,displayNameBase,192) \
TF_RADIO_ID(baseClass,displayNameBase,193) \
TF_RADIO_ID(baseClass,displayNameBase,194) \
TF_RADIO_ID(baseClass,displayNameBase,195) \
TF_RADIO_ID(baseClass,displayNameBase,196) \
TF_RADIO_ID(baseClass,displayNameBase,197) \
TF_RADIO_ID(baseClass,displayNameBase,198) \
TF_RADIO_ID(baseClass,displayNameBase,199) \
TF_RADIO_ID(baseClass,displayNameBase,200) \
TF_RADIO_ID(baseClass,displayNameBase,201) \
TF_RADIO_ID(baseClass,displayNameBase,202) \
TF_RADIO_ID(baseClass,displayNameBase,203) \
TF_RADIO_ID(baseClass,displayNameBase,204) \
TF_RADIO_ID(baseClass,displayNameBase,205) \
TF_RADIO_ID(baseClass,displayNameBase,206) \
TF_RADIO_ID(baseClass,displayNameBase,207) \
TF_RADIO_ID(baseClass,displayNameBase,208) \
TF_RADIO_ID(baseClass,displayNameBase,209) \
TF_RADIO_ID(baseClass,displayNameBase,210) \
TF_RADIO_ID(baseClass,displayNameBase,211) \
TF_RADIO_ID(baseClass,displayNameBase,212) \
TF_RADIO_ID(baseClass,displayNameBase,213) \
TF_RADIO_ID(baseClass,displayNameBase,214) \
TF_RADIO_ID(baseClass,displayNameBase,215) \
TF_RADIO_ID(baseClass,displayNameBase,216) \
TF_RADIO_ID(baseClass,displayNameBase,217) \
TF_RADIO_ID(baseClass,displayNameBase,218) \
TF_RADIO_ID(baseClass,displayNameBase,219) \
TF_RADIO_ID(baseClass,displayNameBase,220) \
TF_RADIO_ID(baseClass,displayNameBase,221) \
TF_RADIO_ID(baseClass,displayNameBase,222) \
TF_RADIO_ID(baseClass,displayNameBase,223) \
TF_RADIO_ID(baseClass,displayNameBase,224) \
TF_RADIO_ID(baseClass,displayNameBase,225) \
TF_RADIO_ID(baseClass,displayNameBase,226) \
TF_RADIO_ID(baseClass,displayNameBase,227) \
TF_RADIO_ID(baseClass,displayNameBase,228) \
TF_RADIO_ID(baseClass,displayNameBase,229) \
TF_RADIO_ID(baseClass,displayNameBase,230) \
TF_RADIO_ID(baseClass,displayNameBase,231) \
TF_RADIO_ID(baseClass,displayNameBase,232) \
TF_RADIO_ID(baseClass,displayNameBase,233) \
TF_RADIO_ID(baseClass,displayNameBase,234) \
TF_RADIO_ID(baseClass,displayNameBase,235) \
TF_RADIO_ID(baseClass,displayNameBase,236) \
TF_RADIO_ID(baseClass,displayNameBase,237) \
TF_RADIO_ID(baseClass,displayNameBase,238) \
TF_RADIO_ID(baseClass,displayNameBase,239) \
TF_RADIO_ID(baseClass,displayNameBase,240) \
TF_RADIO_ID(baseClass,displayNameBase,241) \
TF_RADIO_ID(baseClass,displayNameBase,242) \
TF_RADIO_ID(baseClass,displayNameBase,243) \
TF_RADIO_ID(baseClass,displayNameBase,244) \
TF_RADIO_ID(baseClass,displayNameBase,245) \
TF_RADIO_ID(baseClass,displayNameBase,246) \
TF_RADIO_ID(baseClass,displayNameBase,247) \
TF_RADIO_ID(baseClass,displayNameBase,248) \
TF_RADIO_ID(baseClass,displayNameBase,249) \
TF_RADIO_ID(baseClass,displayNameBase,250) \
TF_RADIO_ID(baseClass,displayNameBase,251) \
TF_RADIO_ID(baseClass,displayNameBase,252) \
TF_RADIO_ID(baseClass,displayNameBase,253) \
TF_RADIO_ID(baseClass,displayNameBase,254) \
TF_RADIO_ID(baseClass,displayNameBase,255) \
TF_RADIO_ID(baseClass,displayNameBase,256) \
TF_RADIO_ID(baseClass,displayNameBase,257) \
TF_RADIO_ID(baseClass,displayNameBase,258) \
TF_RADIO_ID(baseClass,displayNameBase,259) \
TF_RADIO_ID(baseClass,displayNameBase,260) \
TF_RADIO_ID(baseClass,displayNameBase,261) \
TF_RADIO_ID(baseClass,displayNameBase,262) \
TF_RADIO_ID(baseClass,displayNameBase,263) \
TF_RADIO_ID(baseClass,displayNameBase,264) \
TF_RADIO_ID(baseClass,displayNameBase,265) \
TF_RADIO_ID(baseClass,displayNameBase,266) \
TF_RADIO_ID(baseClass,displayNameBase,267) \
TF_RADIO_ID(baseClass,displayNameBase,268) \
TF_RADIO_ID(baseClass,displayNameBase,269) \
TF_RADIO_ID(baseClass,displayNameBase,270) \
TF_RADIO_ID(baseClass,displayNameBase,271) \
TF_RADIO_ID(baseClass,displayNameBase,272) \
TF_RADIO_ID(baseClass,displayNameBase,273) \
TF_RADIO_ID(baseClass,displayNameBase,274) \
TF_RADIO_ID(baseClass,displayNameBase,275) \
TF_RADIO_ID(baseClass,displayNameBase,276) \
TF_RADIO_ID(baseClass,displayNameBase,277) \
TF_RADIO_ID(baseClass,displayNameBase,278) \
TF_RADIO_ID(baseClass,displayNameBase,279) \
TF_RADIO_ID(baseClass,displayNameBase,280) \
TF_RADIO_ID(baseClass,displayNameBase,281) \
TF_RADIO_ID(baseClass,displayNameBase,282) \
TF_RADIO_ID(baseClass,displayNameBase,283) \
TF_RADIO_ID(baseClass,displayNameBase,284) \
TF_RADIO_ID(baseClass,displayNameBase,285) \
TF_RADIO_ID(baseClass,displayNameBase,286) \
TF_RADIO_ID(baseClass,displayNameBase,287) \
TF_RADIO_ID(baseClass,displayNameBase,288) \
TF_RADIO_ID(baseClass,displayNameBase,289) \
TF_RADIO_ID(baseClass,displayNameBase,290) \
TF_RADIO_ID(baseClass,displayNameBase,291) \
TF_RADIO_ID(baseClass,displayNameBase,292) \
TF_RADIO_ID(baseClass,displayNameBase,293) \
TF_RADIO_ID(baseClass,displayNameBase,294) \
TF_RADIO_ID(baseClass,displayNameBase,295) \
TF_RADIO_ID(baseClass,displayNameBase,296) \
TF_RADIO_ID(baseClass,displayNameBase,297) \
TF_RADIO_ID(baseClass,displayNameBase,298) \
TF_RADIO_ID(baseClass,displayNameBase,299) \
TF_RADIO_ID(baseClass,displayNameBase,300) \
TF_RADIO_ID(baseClass,displayNameBase,301) \
TF_RADIO_ID(baseClass,displayNameBase,302) \
TF_RADIO_ID(baseClass,displayNameBase,303) \
TF_RADIO_ID(baseClass,displayNameBase,304) \
TF_RADIO_ID(baseClass,displayNameBase,305) \
TF_RADIO_ID(baseClass,displayNameBase,306) \
TF_RADIO_ID(baseClass,displayNameBase,307) \
TF_RADIO_ID(baseClass,displayNameBase,308) \
TF_RADIO_ID(baseClass,displayNameBase,309) \
TF_RADIO_ID(baseClass,displayNameBase,310) \
TF_RADIO_ID(baseClass,displayNameBase,311) \
TF_RADIO_ID(baseClass,displayNameBase,312) \
TF_RADIO_ID(baseClass,displayNameBase,313) \
TF_RADIO_ID(baseClass,displayNameBase,314) \
TF_RADIO_ID(baseClass,displayNameBase,315) \
TF_RADIO_ID(baseClass,displayNameBase,316) \
TF_RADIO_ID(baseClass,displayNameBase,317) \
TF_RADIO_ID(baseClass,displayNameBase,318) \
TF_RADIO_ID(baseClass,displayNameBase,319) \
TF_RADIO_ID(baseClass,displayNameBase,320) \
TF_RADIO_ID(baseClass,displayNameBase,321) \
TF_RADIO_ID(baseClass,displayNameBase,322) \
TF_RADIO_ID(baseClass,displayNameBase,323) \
TF_RADIO_ID(baseClass,displayNameBase,324) \
TF_RADIO_ID(baseClass,displayNameBase,325) \
TF_RADIO_ID(baseClass,displayNameBase,326) \
TF_RADIO_ID(baseClass,displayNameBase,327) \
TF_RADIO_ID(baseClass,displayNameBase,328) \
TF_RADIO_ID(baseClass,displayNameBase,329) \
TF_RADIO_ID(baseClass,displayNameBase,330) \
TF_RADIO_ID(baseClass,displayNameBase,331) \
TF_RADIO_ID(baseClass,displayNameBase,332) \
TF_RADIO_ID(baseClass,displayNameBase,333) \
TF_RADIO_ID(baseClass,displayNameBase,334) \
TF_RADIO_ID(baseClass,displayNameBase,335) \
TF_RADIO_ID(baseClass,displayNameBase,336) \
TF_RADIO_ID(baseClass,displayNameBase,337) \
TF_RADIO_ID(baseClass,displayNameBase,338) \
TF_RADIO_ID(baseClass,displayNameBase,339) \
TF_RADIO_ID(baseClass,displayNameBase,340) \
TF_RADIO_ID(baseClass,displayNameBase,341) \
TF_RADIO_ID(baseClass,displayNameBase,342) \
TF_RADIO_ID(baseClass,displayNameBase,343) \
TF_RADIO_ID(baseClass,displayNameBase,344) \
TF_RADIO_ID(baseClass,displayNameBase,345) \
TF_RADIO_ID(baseClass,displayNameBase,346) \
TF_RADIO_ID(baseClass,displayNameBase,347) \
TF_RADIO_ID(baseClass,displayNameBase,348) \
TF_RADIO_ID(baseClass,displayNameBase,349) \
TF_RADIO_ID(baseClass,displayNameBase,350) \
TF_RADIO_ID(baseClass,displayNameBase,351) \
TF_RADIO_ID(baseClass,displayNameBase,352) \
TF_RADIO_ID(baseClass,displayNameBase,353) \
TF_RADIO_ID(baseClass,displayNameBase,354) \
TF_RADIO_ID(baseClass,displayNameBase,355) \
TF_RADIO_ID(baseClass,displayNameBase,356) \
TF_RADIO_ID(baseClass,displayNameBase,357) \
TF_RADIO_ID(baseClass,displayNameBase,358) \
TF_RADIO_ID(baseClass,displayNameBase,359) \
TF_RADIO_ID(baseClass,displayNameBase,360) \
TF_RADIO_ID(baseClass,displayNameBase,361) \
TF_RADIO_ID(baseClass,displayNameBase,362) \
TF_RADIO_ID(baseClass,displayNameBase,363) \
TF_RADIO_ID(baseClass,displayNameBase,364) \
TF_RADIO_ID(baseClass,displayNameBase,365) \
TF_RADIO_ID(baseClass,displayNameBase,366) \
TF_RADIO_ID(baseClass,displayNameBase,367) \
TF_RADIO_ID(baseClass,displayNameBase,368) \
TF_RADIO_ID(baseClass,displayNameBase,369) \
TF_RADIO_ID(baseClass,displayNameBase,370) \
TF_RADIO_ID(baseClass,displayNameBase,371) \
TF_RADIO_ID(baseClass,displayNameBase,372) \
TF_RADIO_ID(baseClass,displayNameBase,373) \
TF_RADIO_ID(baseClass,displayNameBase,374) \
TF_RADIO_ID(baseClass,displayNameBase,375) \
TF_RADIO_ID(baseClass,displayNameBase,376) \
TF_RADIO_ID(baseClass,displayNameBase,377) \
TF_RADIO_ID(baseClass,displayNameBase,378) \
TF_RADIO_ID(baseClass,displayNameBase,379) \
TF_RADIO_ID(baseClass,displayNameBase,380) \
TF_RADIO_ID(baseClass,displayNameBase,381) \
TF_RADIO_ID(baseClass,displayNameBase,382) \
TF_RADIO_ID(baseClass,displayNameBase,383) \
TF_RADIO_ID(baseClass,displayNameBase,384) \
TF_RADIO_ID(baseClass,displayNameBase,385) \
TF_RADIO_ID(baseClass,displayNameBase,386) \
TF_RADIO_ID(baseClass,displayNameBase,387) \
TF_RADIO_ID(baseClass,displayNameBase,388) \
TF_RADIO_ID(baseClass,displayNameBase,389) \
TF_RADIO_ID(baseClass,displayNameBase,390) \
TF_RADIO_ID(baseClass,displayNameBase,391) \
TF_RADIO_ID(baseClass,displayNameBase,392) \
TF_RADIO_ID(baseClass,displayNameBase,393) \
TF_RADIO_ID(baseClass,displayNameBase,394) \
TF_RADIO_ID(baseClass,displayNameBase,395) \
TF_RADIO_ID(baseClass,displayNameBase,396) \
TF_RADIO_ID(baseClass,displayNameBase,397) \
TF_RADIO_ID(baseClass,displayNameBase,398) \
TF_RADIO_ID(baseClass,displayNameBase,399) \
TF_RADIO_ID(baseClass,displayNameBase,400) \
TF_RADIO_ID(baseClass,displayNameBase,401) \
TF_RADIO_ID(baseClass,displayNameBase,402) \
TF_RADIO_ID(baseClass,displayNameBase,403) \
TF_RADIO_ID(baseClass,displayNameBase,404) \
TF_RADIO_ID(baseClass,displayNameBase,405) \
TF_RADIO_ID(baseClass,displayNameBase,406) \
TF_RADIO_ID(baseClass,displayNameBase,407) \
TF_RADIO_ID(baseClass,displayNameBase,408) \
TF_RADIO_ID(baseClass,displayNameBase,409) \
TF_RADIO_ID(baseClass,displayNameBase,410) \
TF_RADIO_ID(baseClass,displayNameBase,411) \
TF_RADIO_ID(baseClass,displayNameBase,412) \
TF_RADIO_ID(baseClass,displayNameBase,413) \
TF_RADIO_ID(baseClass,displayNameBase,414) \
TF_RADIO_ID(baseClass,displayNameBase,415) \
TF_RADIO_ID(baseClass,displayNameBase,416) \
TF_RADIO_ID(baseClass,displayNameBase,417) \
TF_RADIO_ID(baseClass,displayNameBase,418) \
TF_RADIO_ID(baseClass,displayNameBase,419) \
TF_RADIO_ID(baseClass,displayNameBase,420) \
TF_RADIO_ID(baseClass,displayNameBase,421) \
TF_RADIO_ID(baseClass,displayNameBase,422) \
TF_RADIO_ID(baseClass,displayNameBase,423) \
TF_RADIO_ID(baseClass,displayNameBase,424) \
TF_RADIO_ID(baseClass,displayNameBase,425) \
TF_RADIO_ID(baseClass,displayNameBase,426) \
TF_RADIO_ID(baseClass,displayNameBase,427) \
TF_RADIO_ID(baseClass,displayNameBase,428) \
TF_RADIO_ID(baseClass,displayNameBase,429) \
TF_RADIO_ID(baseClass,displayNameBase,430) \
TF_RADIO_ID(baseClass,displayNameBase,431) \
TF_RADIO_ID(baseClass,displayNameBase,432) \
TF_RADIO_ID(baseClass,displayNameBase,433) \
TF_RADIO_ID(baseClass,displayNameBase,434) \
TF_RADIO_ID(baseClass,displayNameBase,435) \
TF_RADIO_ID(baseClass,displayNameBase,436) \
TF_RADIO_ID(baseClass,displayNameBase,437) \
TF_RADIO_ID(baseClass,displayNameBase,438) \
TF_RADIO_ID(baseClass,displayNameBase,439) \
TF_RADIO_ID(baseClass,displayNameBase,440) \
TF_RADIO_ID(baseClass,displayNameBase,441) \
TF_RADIO_ID(baseClass,displayNameBase,442) \
TF_RADIO_ID(baseClass,displayNameBase,443) \
TF_RADIO_ID(baseClass,displayNameBase,444) \
TF_RADIO_ID(baseClass,displayNameBase,445) \
TF_RADIO_ID(baseClass,displayNameBase,446) \
TF_RADIO_ID(baseClass,displayNameBase,447) \
TF_RADIO_ID(baseClass,displayNameBase,448) \
TF_RADIO_ID(baseClass,displayNameBase,449) \
TF_RADIO_ID(baseClass,displayNameBase,450) \
TF_RADIO_ID(baseClass,displayNameBase,451) \
TF_RADIO_ID(baseClass,displayNameBase,452) \
TF_RADIO_ID(baseClass,displayNameBase,453) \
TF_RADIO_ID(baseClass,displayNameBase,454) \
TF_RADIO_ID(baseClass,displayNameBase,455) \
TF_RADIO_ID(baseClass,displayNameBase,456) \
TF_RADIO_ID(baseClass,displayNameBase,457) \
TF_RADIO_ID(baseClass,displayNameBase,458) \
TF_RADIO_ID(baseClass,displayNameBase,459) \
TF_RADIO_ID(baseClass,displayNameBase,460) \
TF_RADIO_ID(baseClass,displayNameBase,461) \
TF_RADIO_ID(baseClass,displayNameBase,462) \
TF_RADIO_ID(baseClass,displayNameBase,463) \
TF_RADIO_ID(baseClass,displayNameBase,464) \
TF_RADIO_ID(baseClass,displayNameBase,465) \
TF_RADIO_ID(baseClass,displayNameBase,466) \
TF_RADIO_ID(baseClass,displayNameBase,467) \
TF_RADIO_ID(baseClass,displayNameBase,468) \
TF_RADIO_ID(baseClass,displayNameBase,469) \
TF_RADIO_ID(baseClass,displayNameBase,470) \
TF_RADIO_ID(baseClass,displayNameBase,471) \
TF_RADIO_ID(baseClass,displayNameBase,472) \
TF_RADIO_ID(baseClass,displayNameBase,473) \
TF_RADIO_ID(baseClass,displayNameBase,474) \
TF_RADIO_ID(baseClass,displayNameBase,475) \
TF_RADIO_ID(baseClass,displayNameBase,476) \
TF_RADIO_ID(baseClass,displayNameBase,477) \
TF_RADIO_ID(baseClass,displayNameBase,478) \
TF_RADIO_ID(baseClass,displayNameBase,479) \
TF_RADIO_ID(baseClass,displayNameBase,480) \
TF_RADIO_ID(baseClass,displayNameBase,481) \
TF_RADIO_ID(baseClass,displayNameBase,482) \
TF_RADIO_ID(baseClass,displayNameBase,483) \
TF_RADIO_ID(baseClass,displayNameBase,484) \
TF_RADIO_ID(baseClass,displayNameBase,485) \
TF_RADIO_ID(baseClass,displayNameBase,486) \
TF_RADIO_ID(baseClass,displayNameBase,487) \
TF_RADIO_ID(baseClass,displayNameBase,488) \
TF_RADIO_ID(baseClass,displayNameBase,489) \
TF_RADIO_ID(baseClass,displayNameBase,490) \
TF_RADIO_ID(baseClass,displayNameBase,491) \
TF_RADIO_ID(baseClass,displayNameBase,492) \
TF_RADIO_ID(baseClass,displayNameBase,493) \
TF_RADIO_ID(baseClass,displayNameBase,494) \
TF_RADIO_ID(baseClass,displayNameBase,495) \
TF_RADIO_ID(baseClass,displayNameBase,496) \
TF_RADIO_ID(baseClass,displayNameBase,497) \
TF_RADIO_ID(baseClass,displayNameBase,498) \
TF_RADIO_ID(baseClass,displayNameBase,499) \
TF_RADIO_ID(baseClass,displayNameBase,500) \
TF_RADIO_ID(baseClass,displayNameBase,501) \
TF_RADIO_ID(baseClass,displayNameBase,502) \
TF_RADIO_ID(baseClass,displayNameBase,503) \
TF_RADIO_ID(baseClass,displayNameBase,504) \
TF_RADIO_ID(baseClass,displayNameBase,505) \
TF_RADIO_ID(baseClass,displayNameBase,506) \
TF_RADIO_ID(baseClass,displayNameBase,507) \
TF_RADIO_ID(baseClass,displayNameBase,508) \
TF_RADIO_ID(baseClass,displayNameBase,509) \
TF_RADIO_ID(baseClass,displayNameBase,510) \
TF_RADIO_ID(baseClass,displayNameBase,511) \
TF_RADIO_ID(baseClass,displayNameBase,512) \
TF_RADIO_ID(baseClass,displayNameBase,513) \
TF_RADIO_ID(baseClass,displayNameBase,514) \
TF_RADIO_ID(baseClass,displayNameBase,515) \
TF_RADIO_ID(baseClass,displayNameBase,516) \
TF_RADIO_ID(baseClass,displayNameBase,517) \
TF_RADIO_ID(baseClass,displayNameBase,518) \
TF_RADIO_ID(baseClass,displayNameBase,519) \
TF_RADIO_ID(baseClass,displayNameBase,520) \
TF_RADIO_ID(baseClass,displayNameBase,521) \
TF_RADIO_ID(baseClass,displayNameBase,522) \
TF_RADIO_ID(baseClass,displayNameBase,523) \
TF_RADIO_ID(baseClass,displayNameBase,524) \
TF_RADIO_ID(baseClass,displayNameBase,525) \
TF_RADIO_ID(baseClass,displayNameBase,526) \
TF_RADIO_ID(baseClass,displayNameBase,527) \
TF_RADIO_ID(baseClass,displayNameBase,528) \
TF_RADIO_ID(baseClass,displayNameBase,529) \
TF_RADIO_ID(baseClass,displayNameBase,530) \
TF_RADIO_ID(baseClass,displayNameBase,531) \
TF_RADIO_ID(baseClass,displayNameBase,532) \
TF_RADIO_ID(baseClass,displayNameBase,533) \
TF_RADIO_ID(baseClass,displayNameBase,534) \
TF_RADIO_ID(baseClass,displayNameBase,535) \
TF_RADIO_ID(baseClass,displayNameBase,536) \
TF_RADIO_ID(baseClass,displayNameBase,537) \
TF_RADIO_ID(baseClass,displayNameBase,538) \
TF_RADIO_ID(baseClass,displayNameBase,539) \
TF_RADIO_ID(baseClass,displayNameBase,540) \
TF_RADIO_ID(baseClass,displayNameBase,541) \
TF_RADIO_ID(baseClass,displayNameBase,542) \
TF_RADIO_ID(baseClass,displayNameBase,543) \
TF_RADIO_ID(baseClass,displayNameBase,544) \
TF_RADIO_ID(baseClass,displayNameBase,545) \
TF_RADIO_ID(baseClass,displayNameBase,546) \
TF_RADIO_ID(baseClass,displayNameBase,547) \
TF_RADIO_ID(baseClass,displayNameBase,548) \
TF_RADIO_ID(baseClass,displayNameBase,549) \
TF_RADIO_ID(baseClass,displayNameBase,550) \
TF_RADIO_ID(baseClass,displayNameBase,551) \
TF_RADIO_ID(baseClass,displayNameBase,552) \
TF_RADIO_ID(baseClass,displayNameBase,553) \
TF_RADIO_ID(baseClass,displayNameBase,554) \
TF_RADIO_ID(baseClass,displayNameBase,555) \
TF_RADIO_ID(baseClass,displayNameBase,556) \
TF_RADIO_ID(baseClass,displayNameBase,557) \
TF_RADIO_ID(baseClass,displayNameBase,558) \
TF_RADIO_ID(baseClass,displayNameBase,559) \
TF_RADIO_ID(baseClass,displayNameBase,560) \
TF_RADIO_ID(baseClass,displayNameBase,561) \
TF_RADIO_ID(baseClass,displayNameBase,562) \
TF_RADIO_ID(baseClass,displayNameBase,563) \
TF_RADIO_ID(baseClass,displayNameBase,564) \
TF_RADIO_ID(baseClass,displayNameBase,565) \
TF_RADIO_ID(baseClass,displayNameBase,566) \
TF_RADIO_ID(baseClass,displayNameBase,567) \
TF_RADIO_ID(baseClass,displayNameBase,568) \
TF_RADIO_ID(baseClass,displayNameBase,569) \
TF_RADIO_ID(baseClass,displayNameBase,570) \
TF_RADIO_ID(baseClass,displayNameBase,571) \
TF_RADIO_ID(baseClass,displayNameBase,572) \
TF_RADIO_ID(baseClass,displayNameBase,573) \
TF_RADIO_ID(baseClass,displayNameBase,574) \
TF_RADIO_ID(baseClass,displayNameBase,575) \
TF_RADIO_ID(baseClass,displayNameBase,576) \
TF_RADIO_ID(baseClass,displayNameBase,577) \
TF_RADIO_ID(baseClass,displayNameBase,578) \
TF_RADIO_ID(baseClass,displayNameBase,579) \
TF_RADIO_ID(baseClass,displayNameBase,580) \
TF_RADIO_ID(baseClass,displayNameBase,581) \
TF_RADIO_ID(baseClass,displayNameBase,582) \
TF_RADIO_ID(baseClass,displayNameBase,583) \
TF_RADIO_ID(baseClass,displayNameBase,584) \
TF_RADIO_ID(baseClass,displayNameBase,585) \
TF_RADIO_ID(baseClass,displayNameBase,586) \
TF_RADIO_ID(baseClass,displayNameBase,587) \
TF_RADIO_ID(baseClass,displayNameBase,588) \
TF_RADIO_ID(baseClass,displayNameBase,589) \
TF_RADIO_ID(baseClass,displayNameBase,590) \
TF_RADIO_ID(baseClass,displayNameBase,591) \
TF_RADIO_ID(baseClass,displayNameBase,592) \
TF_RADIO_ID(baseClass,displayNameBase,593) \
TF_RADIO_ID(baseClass,displayNameBase,594) \
TF_RADIO_ID(baseClass,displayNameBase,595) \
TF_RADIO_ID(baseClass,displayNameBase,596) \
TF_RADIO_ID(baseClass,displayNameBase,597) \
TF_RADIO_ID(baseClass,displayNameBase,598) \
TF_RADIO_ID(baseClass,displayNameBase,599) \
TF_RADIO_ID(baseClass,displayNameBase,600) \
TF_RADIO_ID(baseClass,displayNameBase,601) \
TF_RADIO_ID(baseClass,displayNameBase,602) \
TF_RADIO_ID(baseClass,displayNameBase,603) \
TF_RADIO_ID(baseClass,displayNameBase,604) \
TF_RADIO_ID(baseClass,displayNameBase,605) \
TF_RADIO_ID(baseClass,displayNameBase,606) \
TF_RADIO_ID(baseClass,displayNameBase,607) \
TF_RADIO_ID(baseClass,displayNameBase,608) \
TF_RADIO_ID(baseClass,displayNameBase,609) \
TF_RADIO_ID(baseClass,displayNameBase,610) \
TF_RADIO_ID(baseClass,displayNameBase,611) \
TF_RADIO_ID(baseClass,displayNameBase,612) \
TF_RADIO_ID(baseClass,displayNameBase,613) \
TF_RADIO_ID(baseClass,displayNameBase,614) \
TF_RADIO_ID(baseClass,displayNameBase,615) \
TF_RADIO_ID(baseClass,displayNameBase,616) \
TF_RADIO_ID(baseClass,displayNameBase,617) \
TF_RADIO_ID(baseClass,displayNameBase,618) \
TF_RADIO_ID(baseClass,displayNameBase,619) \
TF_RADIO_ID(baseClass,displayNameBase,620) \
TF_RADIO_ID(baseClass,displayNameBase,621) \
TF_RADIO_ID(baseClass,displayNameBase,622) \
TF_RADIO_ID(baseClass,displayNameBase,623) \
TF_RADIO_ID(baseClass,displayNameBase,624) \
TF_RADIO_ID(baseClass,displayNameBase,625) \
TF_RADIO_ID(baseClass,displayNameBase,626) \
TF_RADIO_ID(baseClass,displayNameBase,627) \
TF_RADIO_ID(baseClass,displayNameBase,628) \
TF_RADIO_ID(baseClass,displayNameBase,629) \
TF_RADIO_ID(baseClass,displayNameBase,630) \
TF_RADIO_ID(baseClass,displayNameBase,631) \
TF_RADIO_ID(baseClass,displayNameBase,632) \
TF_RADIO_ID(baseClass,displayNameBase,633) \
TF_RADIO_ID(baseClass,displayNameBase,634) \
TF_RADIO_ID(baseClass,displayNameBase,635) \
TF_RADIO_ID(baseClass,displayNameBase,636) \
TF_RADIO_ID(baseClass,displayNameBase,637) \
TF_RADIO_ID(baseClass,displayNameBase,638) \
TF_RADIO_ID(baseClass,displayNameBase,639) \
TF_RADIO_ID(baseClass,displayNameBase,640) \
TF_RADIO_ID(baseClass,displayNameBase,641) \
TF_RADIO_ID(baseClass,displayNameBase,642) \
TF_RADIO_ID(baseClass,displayNameBase,643) \
TF_RADIO_ID(baseClass,displayNameBase,644) \
TF_RADIO_ID(baseClass,displayNameBase,645) \
TF_RADIO_ID(baseClass,displayNameBase,646) \
TF_RADIO_ID(baseClass,displayNameBase,647) \
TF_RADIO_ID(baseClass,displayNameBase,648) \
TF_RADIO_ID(baseClass,displayNameBase,649) \
TF_RADIO_ID(baseClass,displayNameBase,650) \
TF_RADIO_ID(baseClass,displayNameBase,651) \
TF_RADIO_ID(baseClass,displayNameBase,652) \
TF_RADIO_ID(baseClass,displayNameBase,653) \
TF_RADIO_ID(baseClass,displayNameBase,654) \
TF_RADIO_ID(baseClass,displayNameBase,655) \
TF_RADIO_ID(baseClass,displayNameBase,656) \
TF_RADIO_ID(baseClass,displayNameBase,657) \
TF_RADIO_ID(baseClass,displayNameBase,658) \
TF_RADIO_ID(baseClass,displayNameBase,659) \
TF_RADIO_ID(baseClass,displayNameBase,660) \
TF_RADIO_ID(baseClass,displayNameBase,661) \
TF_RADIO_ID(baseClass,displayNameBase,662) \
TF_RADIO_ID(baseClass,displayNameBase,663) \
TF_RADIO_ID(baseClass,displayNameBase,664) \
TF_RADIO_ID(baseClass,displayNameBase,665) \
TF_RADIO_ID(baseClass,displayNameBase,666) \
TF_RADIO_ID(baseClass,displayNameBase,667) \
TF_RADIO_ID(baseClass,displayNameBase,668) \
TF_RADIO_ID(baseClass,displayNameBase,669) \
TF_RADIO_ID(baseClass,displayNameBase,670) \
TF_RADIO_ID(baseClass,displayNameBase,671) \
TF_RADIO_ID(baseClass,displayNameBase,672) \
TF_RADIO_ID(baseClass,displayNameBase,673) \
TF_RADIO_ID(baseClass,displayNameBase,674) \
TF_RADIO_ID(baseClass,displayNameBase,675) \
TF_RADIO_ID(baseClass,displayNameBase,676) \
TF_RADIO_ID(baseClass,displayNameBase,677) \
TF_RADIO_ID(baseClass,displayNameBase,678) \
TF_RADIO_ID(baseClass,displayNameBase,679) \
TF_RADIO_ID(baseClass,displayNameBase,680) \
TF_RADIO_ID(baseClass,displayNameBase,681) \
TF_RADIO_ID(baseClass,displayNameBase,682) \
TF_RADIO_ID(baseClass,displayNameBase,683) \
TF_RADIO_ID(baseClass,displayNameBase,684) \
TF_RADIO_ID(baseClass,displayNameBase,685) \
TF_RADIO_ID(baseClass,displayNameBase,686) \
TF_RADIO_ID(baseClass,displayNameBase,687) \
TF_RADIO_ID(baseClass,displayNameBase,688) \
TF_RADIO_ID(baseClass,displayNameBase,689) \
TF_RADIO_ID(baseClass,displayNameBase,690) \
TF_RADIO_ID(baseClass,displayNameBase,691) \
TF_RADIO_ID(baseClass,displayNameBase,692) \
TF_RADIO_ID(baseClass,displayNameBase,693) \
TF_RADIO_ID(baseClass,displayNameBase,694) \
TF_RADIO_ID(baseClass,displayNameBase,695) \
TF_RADIO_ID(baseClass,displayNameBase,696) \
TF_RADIO_ID(baseClass,displayNameBase,697) \
TF_RADIO_ID(baseClass,displayNameBase,698) \
TF_RADIO_ID(baseClass,displayNameBase,699) \
TF_RADIO_ID(baseClass,displayNameBase,700) \
TF_RADIO_ID(baseClass,displayNameBase,701) \
TF_RADIO_ID(baseClass,displayNameBase,702) \
TF_RADIO_ID(baseClass,displayNameBase,703) \
TF_RADIO_ID(baseClass,displayNameBase,704) \
TF_RADIO_ID(baseClass,displayNameBase,705) \
TF_RADIO_ID(baseClass,displayNameBase,706) \
TF_RADIO_ID(baseClass,displayNameBase,707) \
TF_RADIO_ID(baseClass,displayNameBase,708) \
TF_RADIO_ID(baseClass,displayNameBase,709) \
TF_RADIO_ID(baseClass,displayNameBase,710) \
TF_RADIO_ID(baseClass,displayNameBase,711) \
TF_RADIO_ID(baseClass,displayNameBase,712) \
TF_RADIO_ID(baseClass,displayNameBase,713) \
TF_RADIO_ID(baseClass,displayNameBase,714) \
TF_RADIO_ID(baseClass,displayNameBase,715) \
TF_RADIO_ID(baseClass,displayNameBase,716) \
TF_RADIO_ID(baseClass,displayNameBase,717) \
TF_RADIO_ID(baseClass,displayNameBase,718) \
TF_RADIO_ID(baseClass,displayNameBase,719) \
TF_RADIO_ID(baseClass,displayNameBase,720) \
TF_RADIO_ID(baseClass,displayNameBase,721) \
TF_RADIO_ID(baseClass,displayNameBase,722) \
TF_RADIO_ID(baseClass,displayNameBase,723) \
TF_RADIO_ID(baseClass,displayNameBase,724) \
TF_RADIO_ID(baseClass,displayNameBase,725) \
TF_RADIO_ID(baseClass,displayNameBase,726) \
TF_RADIO_ID(baseClass,displayNameBase,727) \
TF_RADIO_ID(baseClass,displayNameBase,728) \
TF_RADIO_ID(baseClass,displayNameBase,729) \
TF_RADIO_ID(baseClass,displayNameBase,730) \
TF_RADIO_ID(baseClass,displayNameBase,731) \
TF_RADIO_ID(baseClass,displayNameBase,732) \
TF_RADIO_ID(baseClass,displayNameBase,733) \
TF_RADIO_ID(baseClass,displayNameBase,734) \
TF_RADIO_ID(baseClass,displayNameBase,735) \
TF_RADIO_ID(baseClass,displayNameBase,736) \
TF_RADIO_ID(baseClass,displayNameBase,737) \
TF_RADIO_ID(baseClass,displayNameBase,738) \
TF_RADIO_ID(baseClass,displayNameBase,739) \
TF_RADIO_ID(baseClass,displayNameBase,740) \
TF_RADIO_ID(baseClass,displayNameBase,741) \
TF_RADIO_ID(baseClass,displayNameBase,742) \
TF_RADIO_ID(baseClass,displayNameBase,743) \
TF_RADIO_ID(baseClass,displayNameBase,744) \
TF_RADIO_ID(baseClass,displayNameBase,745) \
TF_RADIO_ID(baseClass,displayNameBase,746) \
TF_RADIO_ID(baseClass,displayNameBase,747) \
TF_RADIO_ID(baseClass,displayNameBase,748) \
TF_RADIO_ID(baseClass,displayNameBase,749) \
TF_RADIO_ID(baseClass,displayNameBase,750) \
TF_RADIO_ID(baseClass,displayNameBase,751) \
TF_RADIO_ID(baseClass,displayNameBase,752) \
TF_RADIO_ID(baseClass,displayNameBase,753) \
TF_RADIO_ID(baseClass,displayNameBase,754) \
TF_RADIO_ID(baseClass,displayNameBase,755) \
TF_RADIO_ID(baseClass,displayNameBase,756) \
TF_RADIO_ID(baseClass,displayNameBase,757) \
TF_RADIO_ID(baseClass,displayNameBase,758) \
TF_RADIO_ID(baseClass,displayNameBase,759) \
TF_RADIO_ID(baseClass,displayNameBase,760) \
TF_RADIO_ID(baseClass,displayNameBase,761) \
TF_RADIO_ID(baseClass,displayNameBase,762) \
TF_RADIO_ID(baseClass,displayNameBase,763) \
TF_RADIO_ID(baseClass,displayNameBase,764) \
TF_RADIO_ID(baseClass,displayNameBase,765) \
TF_RADIO_ID(baseClass,displayNameBase,766) \
TF_RADIO_ID(baseClass,displayNameBase,767) \
TF_RADIO_ID(baseClass,displayNameBase,768) \
TF_RADIO_ID(baseClass,displayNameBase,769) \
TF_RADIO_ID(baseClass,displayNameBase,770) \
TF_RADIO_ID(baseClass,displayNameBase,771) \
TF_RADIO_ID(baseClass,displayNameBase,772) \
TF_RADIO_ID(baseClass,displayNameBase,773) \
TF_RADIO_ID(baseClass,displayNameBase,774) \
TF_RADIO_ID(baseClass,displayNameBase,775) \
TF_RADIO_ID(baseClass,displayNameBase,776) \
TF_RADIO_ID(baseClass,displayNameBase,777) \
TF_RADIO_ID(baseClass,displayNameBase,778) \
TF_RADIO_ID(baseClass,displayNameBase,779) \
TF_RADIO_ID(baseClass,displayNameBase,780) \
TF_RADIO_ID(baseClass,displayNameBase,781) \
TF_RADIO_ID(baseClass,displayNameBase,782) \
TF_RADIO_ID(baseClass,displayNameBase,783) \
TF_RADIO_ID(baseClass,displayNameBase,784) \
TF_RADIO_ID(baseClass,displayNameBase,785) \
TF_RADIO_ID(baseClass,displayNameBase,786) \
TF_RADIO_ID(baseClass,displayNameBase,787) \
TF_RADIO_ID(baseClass,displayNameBase,788) \
TF_RADIO_ID(baseClass,displayNameBase,789) \
TF_RADIO_ID(baseClass,displayNameBase,790) \
TF_RADIO_ID(baseClass,displayNameBase,791) \
TF_RADIO_ID(baseClass,displayNameBase,792) \
TF_RADIO_ID(baseClass,displayNameBase,793) \
TF_RADIO_ID(baseClass,displayNameBase,794) \
TF_RADIO_ID(baseClass,displayNameBase,795) \
TF_RADIO_ID(baseClass,displayNameBase,796) \
TF_RADIO_ID(baseClass,displayNameBase,797) \
TF_RADIO_ID(baseClass,displayNameBase,798) \
TF_RADIO_ID(baseClass,displayNameBase,799) \
TF_RADIO_ID(baseClass,displayNameBase,800) \
TF_RADIO_ID(baseClass,displayNameBase,801) \
TF_RADIO_ID(baseClass,displayNameBase,802) \
TF_RADIO_ID(baseClass,displayNameBase,803) \
TF_RADIO_ID(baseClass,displayNameBase,804) \
TF_RADIO_ID(baseClass,displayNameBase,805) \
TF_RADIO_ID(baseClass,displayNameBase,806) \
TF_RADIO_ID(baseClass,displayNameBase,807) \
TF_RADIO_ID(baseClass,displayNameBase,808) \
TF_RADIO_ID(baseClass,displayNameBase,809) \
TF_RADIO_ID(baseClass,displayNameBase,810) \
TF_RADIO_ID(baseClass,displayNameBase,811) \
TF_RADIO_ID(baseClass,displayNameBase,812) \
TF_RADIO_ID(baseClass,displayNameBase,813) \
TF_RADIO_ID(baseClass,displayNameBase,814) \
TF_RADIO_ID(baseClass,displayNameBase,815) \
TF_RADIO_ID(baseClass,displayNameBase,816) \
TF_RADIO_ID(baseClass,displayNameBase,817) \
TF_RADIO_ID(baseClass,displayNameBase,818) \
TF_RADIO_ID(baseClass,displayNameBase,819) \
TF_RADIO_ID(baseClass,displayNameBase,820) \
TF_RADIO_ID(baseClass,displayNameBase,821) \
TF_RADIO_ID(baseClass,displayNameBase,822) \
TF_RADIO_ID(baseClass,displayNameBase,823) \
TF_RADIO_ID(baseClass,displayNameBase,824) \
TF_RADIO_ID(baseClass,displayNameBase,825) \
TF_RADIO_ID(baseClass,displayNameBase,826) \
TF_RADIO_ID(baseClass,displayNameBase,827) \
TF_RADIO_ID(baseClass,displayNameBase,828) \
TF_RADIO_ID(baseClass,displayNameBase,829) \
TF_RADIO_ID(baseClass,displayNameBase,830) \
TF_RADIO_ID(baseClass,displayNameBase,831) \
TF_RADIO_ID(baseClass,displayNameBase,832) \
TF_RADIO_ID(baseClass,displayNameBase,833) \
TF_RADIO_ID(baseClass,displayNameBase,834) \
TF_RADIO_ID(baseClass,displayNameBase,835) \
TF_RADIO_ID(baseClass,displayNameBase,836) \
TF_RADIO_ID(baseClass,displayNameBase,837) \
TF_RADIO_ID(baseClass,displayNameBase,838) \
TF_RADIO_ID(baseClass,displayNameBase,839) \
TF_RADIO_ID(baseClass,displayNameBase,840) \
TF_RADIO_ID(baseClass,displayNameBase,841) \
TF_RADIO_ID(baseClass,displayNameBase,842) \
TF_RADIO_ID(baseClass,displayNameBase,843) \
TF_RADIO_ID(baseClass,displayNameBase,844) \
TF_RADIO_ID(baseClass,displayNameBase,845) \
TF_RADIO_ID(baseClass,displayNameBase,846) \
TF_RADIO_ID(baseClass,displayNameBase,847) \
TF_RADIO_ID(baseClass,displayNameBase,848) \
TF_RADIO_ID(baseClass,displayNameBase,849) \
TF_RADIO_ID(baseClass,displayNameBase,850) \
TF_RADIO_ID(baseClass,displayNameBase,851) \
TF_RADIO_ID(baseClass,displayNameBase,852) \
TF_RADIO_ID(baseClass,displayNameBase,853) \
TF_RADIO_ID(baseClass,displayNameBase,854) \
TF_RADIO_ID(baseClass,displayNameBase,855) \
TF_RADIO_ID(baseClass,displayNameBase,856) \
TF_RADIO_ID(baseClass,displayNameBase,857) \
TF_RADIO_ID(baseClass,displayNameBase,858) \
TF_RADIO_ID(baseClass,displayNameBase,859) \
TF_RADIO_ID(baseClass,displayNameBase,860) \
TF_RADIO_ID(baseClass,displayNameBase,861) \
TF_RADIO_ID(baseClass,displayNameBase,862) \
TF_RADIO_ID(baseClass,displayNameBase,863) \
TF_RADIO_ID(baseClass,displayNameBase,864) \
TF_RADIO_ID(baseClass,displayNameBase,865) \
TF_RADIO_ID(baseClass,displayNameBase,866) \
TF_RADIO_ID(baseClass,displayNameBase,867) \
TF_RADIO_ID(baseClass,displayNameBase,868) \
TF_RADIO_ID(baseClass,displayNameBase,869) \
TF_RADIO_ID(baseClass,displayNameBase,870) \
TF_RADIO_ID(baseClass,displayNameBase,871) \
TF_RADIO_ID(baseClass,displayNameBase,872) \
TF_RADIO_ID(baseClass,displayNameBase,873) \
TF_RADIO_ID(baseClass,displayNameBase,874) \
TF_RADIO_ID(baseClass,displayNameBase,875) \
TF_RADIO_ID(baseClass,displayNameBase,876) \
TF_RADIO_ID(baseClass,displayNameBase,877) \
TF_RADIO_ID(baseClass,displayNameBase,878) \
TF_RADIO_ID(baseClass,displayNameBase,879) \
TF_RADIO_ID(baseClass,displayNameBase,880) \
TF_RADIO_ID(baseClass,displayNameBase,881) \
TF_RADIO_ID(baseClass,displayNameBase,882) \
TF_RADIO_ID(baseClass,displayNameBase,883) \
TF_RADIO_ID(baseClass,displayNameBase,884) \
TF_RADIO_ID(baseClass,displayNameBase,885) \
TF_RADIO_ID(baseClass,displayNameBase,886) \
TF_RADIO_ID(baseClass,displayNameBase,887) \
TF_RADIO_ID(baseClass,displayNameBase,888) \
TF_RADIO_ID(baseClass,displayNameBase,889) \
TF_RADIO_ID(baseClass,displayNameBase,890) \
TF_RADIO_ID(baseClass,displayNameBase,891) \
TF_RADIO_ID(baseClass,displayNameBase,892) \
TF_RADIO_ID(baseClass,displayNameBase,893) \
TF_RADIO_ID(baseClass,displayNameBase,894) \
TF_RADIO_ID(baseClass,displayNameBase,895) \
TF_RADIO_ID(baseClass,displayNameBase,896) \
TF_RADIO_ID(baseClass,displayNameBase,897) \
TF_RADIO_ID(baseClass,displayNameBase,898) \
TF_RADIO_ID(baseClass,displayNameBase,899) \
TF_RADIO_ID(baseClass,displayNameBase,900) \
TF_RADIO_ID(baseClass,displayNameBase,901) \
TF_RADIO_ID(baseClass,displayNameBase,902) \
TF_RADIO_ID(baseClass,displayNameBase,903) \
TF_RADIO_ID(baseClass,displayNameBase,904) \
TF_RADIO_ID(baseClass,displayNameBase,905) \
TF_RADIO_ID(baseClass,displayNameBase,906) \
TF_RADIO_ID(baseClass,displayNameBase,907) \
TF_RADIO_ID(baseClass,displayNameBase,908) \
TF_RADIO_ID(baseClass,displayNameBase,909) \
TF_RADIO_ID(baseClass,displayNameBase,910) \
TF_RADIO_ID(baseClass,displayNameBase,911) \
TF_RADIO_ID(baseClass,displayNameBase,912) \
TF_RADIO_ID(baseClass,displayNameBase,913) \
TF_RADIO_ID(baseClass,displayNameBase,914) \
TF_RADIO_ID(baseClass,displayNameBase,915) \
TF_RADIO_ID(baseClass,displayNameBase,916) \
TF_RADIO_ID(baseClass,displayNameBase,917) \
TF_RADIO_ID(baseClass,displayNameBase,918) \
TF_RADIO_ID(baseClass,displayNameBase,919) \
TF_RADIO_ID(baseClass,displayNameBase,920) \
TF_RADIO_ID(baseClass,displayNameBase,921) \
TF_RADIO_ID(baseClass,displayNameBase,922) \
TF_RADIO_ID(baseClass,displayNameBase,923) \
TF_RADIO_ID(baseClass,displayNameBase,924) \
TF_RADIO_ID(baseClass,displayNameBase,925) \
TF_RADIO_ID(baseClass,displayNameBase,926) \
TF_RADIO_ID(baseClass,displayNameBase,927) \
TF_RADIO_ID(baseClass,displayNameBase,928) \
TF_RADIO_ID(baseClass,displayNameBase,929) \
TF_RADIO_ID(baseClass,displayNameBase,930) \
TF_RADIO_ID(baseClass,displayNameBase,931) \
TF_RADIO_ID(baseClass,displayNameBase,932) \
TF_RADIO_ID(baseClass,displayNameBase,933) \
TF_RADIO_ID(baseClass,displayNameBase,934) \
TF_RADIO_ID(baseClass,displayNameBase,935) \
TF_RADIO_ID(baseClass,displayNameBase,936) \
TF_RADIO_ID(baseClass,displayNameBase,937) \
TF_RADIO_ID(baseClass,displayNameBase,938) \
TF_RADIO_ID(baseClass,displayNameBase,939) \
TF_RADIO_ID(baseClass,displayNameBase,940) \
TF_RADIO_ID(baseClass,displayNameBase,941) \
TF_RADIO_ID(baseClass,displayNameBase,942) \
TF_RADIO_ID(baseClass,displayNameBase,943) \
TF_RADIO_ID(baseClass,displayNameBase,944) \
TF_RADIO_ID(baseClass,displayNameBase,945) \
TF_RADIO_ID(baseClass,displayNameBase,946) \
TF_RADIO_ID(baseClass,displayNameBase,947) \
TF_RADIO_ID(baseClass,displayNameBase,948) \
TF_RADIO_ID(baseClass,displayNameBase,949) \
TF_RADIO_ID(baseClass,displayNameBase,950) \
TF_RADIO_ID(baseClass,displayNameBase,951) \
TF_RADIO_ID(baseClass,displayNameBase,952) \
TF_RADIO_ID(baseClass,displayNameBase,953) \
TF_RADIO_ID(baseClass,displayNameBase,954) \
TF_RADIO_ID(baseClass,displayNameBase,955) \
TF_RADIO_ID(baseClass,displayNameBase,956) \
TF_RADIO_ID(baseClass,displayNameBase,957) \
TF_RADIO_ID(baseClass,displayNameBase,958) \
TF_RADIO_ID(baseClass,displayNameBase,959) \
TF_RADIO_ID(baseClass,displayNameBase,960) \
TF_RADIO_ID(baseClass,displayNameBase,961) \
TF_RADIO_ID(baseClass,displayNameBase,962) \
TF_RADIO_ID(baseClass,displayNameBase,963) \
TF_RADIO_ID(baseClass,displayNameBase,964) \
TF_RADIO_ID(baseClass,displayNameBase,965) \
TF_RADIO_ID(baseClass,displayNameBase,966) \
TF_RADIO_ID(baseClass,displayNameBase,967) \
TF_RADIO_ID(baseClass,displayNameBase,968) \
TF_RADIO_ID(baseClass,displayNameBase,969) \
TF_RADIO_ID(baseClass,displayNameBase,970) \
TF_RADIO_ID(baseClass,displayNameBase,971) \
TF_RADIO_ID(baseClass,displayNameBase,972) \
TF_RADIO_ID(baseClass,displayNameBase,973) \
TF_RADIO_ID(baseClass,displayNameBase,974) \
TF_RADIO_ID(baseClass,displayNameBase,975) \
TF_RADIO_ID(baseClass,displayNameBase,976) \
TF_RADIO_ID(baseClass,displayNameBase,977) \
TF_RADIO_ID(baseClass,displayNameBase,978) \
TF_RADIO_ID(baseClass,displayNameBase,979) \
TF_RADIO_ID(baseClass,displayNameBase,980) \
TF_RADIO_ID(baseClass,displayNameBase,981) \
TF_RADIO_ID(baseClass,displayNameBase,982) \
TF_RADIO_ID(baseClass,displayNameBase,983) \
TF_RADIO_ID(baseClass,displayNameBase,984) \
TF_RADIO_ID(baseClass,displayNameBase,985) \
TF_RADIO_ID(baseClass,displayNameBase,986) \
TF_RADIO_ID(baseClass,displayNameBase,987) \
TF_RADIO_ID(baseClass,displayNameBase,988) \
TF_RADIO_ID(baseClass,displayNameBase,989) \
TF_RADIO_ID(baseClass,displayNameBase,990) \
TF_RADIO_ID(baseClass,displayNameBase,991) \
TF_RADIO_ID(baseClass,displayNameBase,992) \
TF_RADIO_ID(baseClass,displayNameBase,993) \
TF_RADIO_ID(baseClass,displayNameBase,994) \
TF_RADIO_ID(baseClass,displayNameBase,995) \
TF_RADIO_ID(baseClass,displayNameBase,996) \
TF_RADIO_ID(baseClass,displayNameBase,997) \
TF_RADIO_ID(baseClass,displayNameBase,998) \
TF_RADIO_ID(baseClass,displayNameBase,999) \
TF_RADIO_ID(baseClass,displayNameBase,1000)

