#define SW_EDIT	1400
#define SW_CHANNEL	1604
#define ID_ADDITIONAL 12345
#define ID_SPEAKERS 123456
#define LR_EDIT	1410
#define LR_CHANNEL	1411

#define SHIFTL 42
#define CTRLL 29
#define ALTL 56
#define ACTIVE_CHANNEL_OFFSET 0
#define VOLUME_OFFSET 1
#define RADIO_OWNER 7
#define SPEAKER_OFFSET 8
#define POWER_OFFSET 9


#define TF_FREQ_OFFSET 2;
#define TF_FREQ_ROUND_POWER 10;

#define TF_MAX_CHANNELS 8;
#define TF_MIN_SW_FREQ 30;
#define TF_MAX_SW_FREQ 512;

#define TF_MAX_LR_CHANNELS 9;

#define TF_MIN_ASIP_FREQ 30;
#define TF_MAX_ASIP_FREQ 87;

#define TF_MIN_DD_FREQ 32;
#define TF_MAX_DD_FREQ 41;

#define TF_SW_STEREO_OFFSET TF_FREQ_OFFSET + 1;
#define TF_LR_STEREO_OFFSET TF_FREQ_OFFSET + 1;
#define TF_MAX_STEREO 3;

#define TF_CODE_OFFSET TF_SW_STEREO_OFFSET + 1;
#define TF_ADDITIONAL_CHANNEL_OFFSET TF_CODE_OFFSET + 1;
#define TF_ADDITIONAL_STEREO_OFFSET TF_ADDITIONAL_CHANNEL_OFFSET + 1;

#define TF_LR_SPEAKER_OFFSET 8;
#define TF_SW_SPEAKER_OFFSET 8;
