name = "Task Force Arrowhead Radio 0.9.8";
picture = "task_force_arrowhead_logo.paa";
actionName = "Website";
action = "http://radio.task-force.ru/en";
description = "Task Force Arma 3 Radio TeamSpeak Plugin";
logo = "task_force_arrowhead_logo.paa";
logoOver = "manw_winner_addon_1st_emblem.paa";
tooltip = "Task Force Arrowhead Radio";
tooltipOwned = "Task Force Arrowhead Radio";
overview = "War is not only about moving, waiting and engaging targets. It is also about communication. Task Force Arrowhead Radio provides a way to dramatically increase gameplay realism and atmosphere by seamless integration with TeamSpeak.";
author = "TFAR Team";
overviewPicture = "task_force_arrowhead_logo.paa";
overviewText = "Task Force Arrowhead Radio";
overviewFootnote = "<br /><br /><t color='#999999'>This content is under APL-SA License.<t />";