FREQ_OFFSET = 2;
FREQ_ROUND_POWER = 10;

MAX_CHANNELS = 8;
MIN_SW_FREQ = 30;
MAX_SW_FREQ = 512;

MAX_LR_CHANNELS = 9;

MIN_ASIP_FREQ = 30;
MAX_ASIP_FREQ = 87;

SW_STEREO_OFFSET = FREQ_OFFSET + MAX_CHANNELS + 1;
LR_STEREO_OFFSET = FREQ_OFFSET + MAX_LR_CHANNELS + 1;
MAX_STEREO = 3;