name: HEMTT

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v6
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT check
        run: hemtt check
